spring.datasource.url=jdbc:postgresql://localhost:5432/gestao-vagas
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

security.token.secret=5daf46f6-bf31-4659-ba5f-6065820b8753
security.token.secret.candidate=26632b2c-60c6-4a02-9ed4-8571861a662b